### ISSUE TITLE
PGFPlots fails in 1.3-rc2

### ISSUE THREAD

**Issue by feanor12** [JuliaTeX/PGFPlots.jl#126] opened 2019-09-18 14:47 UTC
I tried to use pgfplots in 1.3-rc2 and if I want to switch to the pgf-backend I get the following.

```
pgfplots()
[ Info: Precompiling PGFPlots [3b7a836e-365b-5785-a47d-02c71176b4aa]
ERROR: LoadError: LoadError: InitError: ccall: could not find function fftw_threads_set_callback in library C:\Users\mpus\.julia\packages\FFTW\xi4tZ\deps\usr\bin\libfftw3-3.dll
Stacktrace:
 [1] __init__() at C:\Users\mpus\.julia\packages\FFTW\xi4tZ\src\FFTW.jl:60
 [2] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:692
 [3] _require_from_serialized(::String) at .\loading.jl:743
 [4] _require(::Base.PkgId) at .\loading.jl:1034
 [5] require(::Base.PkgId) at .\loading.jl:922
 [6] require(::Module, ::Symbol) at .\loading.jl:917
 [7] include at .\boot.jl:328 [inlined]
 [8] include_relative(::Module, ::String) at .\loading.jl:1105
 [9] include at .\Base.jl:31 [inlined]
 [10] include(::String) at C:\Users\mpus\.julia\packages\ImageCore\NvFJi\src\ImageCore.jl:3
 [11] top-level scope at C:\Users\mpus\.julia\packages\ImageCore\NvFJi\src\ImageCore.jl:96
 [12] include at .\boot.jl:328 [inlined]
 [13] include_relative(::Module, ::String) at .\loading.jl:1105
 [14] include(::Module, ::String) at .\Base.jl:31
 [15] top-level scope at none:2
 [16] eval at .\boot.jl:330 [inlined]
 [17] eval(::Expr) at .\client.jl:433
 [18] top-level scope at .\none:3
during initialization of module FFTW
in expression starting at C:\Users\mpus\.julia\packages\ImageCore\NvFJi\src\functions.jl:1
in expression starting at C:\Users\mpus\.julia\packages\ImageCore\NvFJi\src\ImageCore.jl:96
ERROR: LoadError: Failed to precompile ImageCore [a09fc81d-aa75-5fe9-8630-4744c3626534] to C:\Users\mpus\.julia\compiled\v1.3\ImageCore\cqNLm_tQSx9.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include(::Module, ::String) at .\Base.jl:31
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:330 [inlined]
 [11] eval(::Expr) at .\client.jl:433
 [12] top-level scope at .\none:3
in expression starting at C:\Users\mpus\.julia\packages\Images\BEHlD\src\Images.jl:46
ERROR: LoadError: LoadError: Failed to precompile Images [916415d5-f1e6-5110-898d-aaa5f9f070e0] to C:\Users\mpus\.julia\compiled\v1.3\Images\H8Vxc_tQSx9.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] include at .\boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1105
 [8] include at .\Base.jl:31 [inlined]
 [9] include(::String) at C:\Users\mpus\.julia\packages\PGFPlots\0APN1\src\PGFPlots.jl:1
 [10] top-level scope at C:\Users\mpus\.julia\packages\PGFPlots\0APN1\src\PGFPlots.jl:42
 [11] include at .\boot.jl:328 [inlined]
 [12] include_relative(::Module, ::String) at .\loading.jl:1105
 [13] include(::Module, ::String) at .\Base.jl:31
 [14] top-level scope at none:2
 [15] eval at .\boot.jl:330 [inlined]
 [16] eval(::Expr) at .\client.jl:433
 [17] top-level scope at .\none:3
in expression starting at C:\Users\mpus\.julia\packages\PGFPlots\0APN1\src\colormaps.jl:5
in expression starting at C:\Users\mpus\.julia\packages\PGFPlots\0APN1\src\PGFPlots.jl:42
ERROR: Failed to precompile PGFPlots [3b7a836e-365b-5785-a47d-02c71176b4aa] to C:\Users\mpus\.julia\compiled\v1.3\PGFPlots\XxINN_tQSx9.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1283
 [3] _require(::Base.PkgId) at .\loading.jl:1024
 [4] require(::Base.PkgId) at .\loading.jl:922
 [5] require(::Module, ::Symbol) at .\loading.jl:917
 [6] top-level scope at C:\Users\mpus\.julia\packages\Plots\h3o4c\src\backends.jl:292
 [7] eval at .\boot.jl:330 [inlined]
 [8] _initialize_backend(::Plots.PGFPlotsBackend) at C:\Users\mpus\.julia\packages\Plots\h3o4c\src\backends.jl:291
 [9] backend(::Plots.PGFPlotsBackend) at C:\Users\mpus\.julia\packages\Plots\h3o4c\src\backends.jl:177
 [10] #pgfplots#270 at C:\Users\mpus\.julia\packages\Plots\h3o4c\src\backends.jl:33 [inlined]
 [11] pgfplots() at C:\Users\mpus\.julia\packages\Plots\h3o4c\src\backends.jl:33
 [12] top-level scope at REPL[9]:1
```

**Comment by mykelk** [comment] 2019-09-18 15:47
I just did a fresh install of 1.3-rc2 on Windows, but was not able to reproduce your issue:
```
julia> using Plots
[ Info: Precompiling Plots [91a5bcdd-55d7-5caf-9e0b-520d859cae80]

julia> pgfplots()
[ Info: Precompiling PGFPlots [3b7a836e-365b-5785-a47d-02c71176b4aa]
Plots.PGFPlotsBackend()

(v1.3) pkg> st
    Status `C:\Users\mykel\.julia\environments\v1.3\Project.toml`
  [7a1cc6ca] FFTW v1.0.0
  [3b7a836e] PGFPlots v3.1.3
  [91a5bcdd] Plots v0.26.3

julia> versioninfo()
Julia Version 1.3.0-rc2.0
Commit a04936e3e0 (2019-09-12 19:49 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = emacs
```

**Comment by feanor12** [comment] 2019-09-18 16:10
The only difference was:

Environment:
  JULIA_NUM_THREADS = 4

After removing the environment variable it worked.

**Comment by mykelk** [comment] 2019-09-18 16:34
Wow, that sounds like an issue for FFTW.jl. Can you file an issue there?

**Comment by stevengj** [comment] 2019-09-18 19:44
Should be fixed by JuliaMath/FFTW.jl#112.

**Closed** 2019-09-18 19:58 UTC
